name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-scripts

      - name: Publish to npm
        run: bunx npm login && bun publish --no-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
